// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBRcur6QhmZibFR1SD4WxU7Ssls1Uulaw',
    appId: '1:329799393413:web:9c54eed9e08556567149ec',
    messagingSenderId: '329799393413',
    projectId: 'mediclic-fe054',
    authDomain: 'mediclic-fe054.firebaseapp.com',
    storageBucket: 'mediclic-fe054.firebasestorage.app',
    measurementId: 'G-JVKHKG0MVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtS_VYSuUTQggv58mQqsqcAP3NF_5r1xw',
    appId: '1:329799393413:android:e457f1144da7d7e87149ec',
    messagingSenderId: '329799393413',
    projectId: 'mediclic-fe054',
    storageBucket: 'mediclic-fe054.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmek0MZlhR-a2pzfo27i4KodOhXXo6umQ',
    appId: '1:329799393413:ios:85327c0e88ca3f0d7149ec',
    messagingSenderId: '329799393413',
    projectId: 'mediclic-fe054',
    storageBucket: 'mediclic-fe054.firebasestorage.app',
    iosBundleId: 'com.example.mediclic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmek0MZlhR-a2pzfo27i4KodOhXXo6umQ',
    appId: '1:329799393413:ios:85327c0e88ca3f0d7149ec',
    messagingSenderId: '329799393413',
    projectId: 'mediclic-fe054',
    storageBucket: 'mediclic-fe054.firebasestorage.app',
    iosBundleId: 'com.example.mediclic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBRcur6QhmZibFR1SD4WxU7Ssls1Uulaw',
    appId: '1:329799393413:web:4070743aa8fe50de7149ec',
    messagingSenderId: '329799393413',
    projectId: 'mediclic-fe054',
    authDomain: 'mediclic-fe054.firebaseapp.com',
    storageBucket: 'mediclic-fe054.firebasestorage.app',
    measurementId: 'G-EPGBELERR9',
  );
}
